[
{"content":{"body":"if a proxy returns configurable: false for property \"x\", why future calls return true throws an error? (I know it is maintaining invariant) it can also silently change configurable to false IMO","msgtype":"m.text"},"ts":1696118933045,"senderName":"Jack Works","senderId":"@jackworks:matrix.org","id":"$wIia91HRErKdLrSu6vTu8rZku9sTVS6M-V8Diwob8w8"},
{"content":{"body":"https://github.com/Jack-Works/proposal-module-sync-assert","m.mentions":{},"msgtype":"m.text"},"ts":1696121112405,"senderName":"Jack Works","senderId":"@jackworks:matrix.org","id":"$SaTml1gOpViLYuVbzG97jx5gwrIcr_P7RcNPL7wpNkc"},
{"content":{"body":"Why would it be better to silently fail to recognize a bug?","msgtype":"m.text"},"ts":1696133109877,"senderName":"ljharb","senderId":"@ljharb:matrix.org","id":"$JRx_OXXfk-rNW7RlaPOJRzzH5tqJuw_Hdlu0sZEnM1k"},
{"content":{"body":"arguably it could have just not called the trap once the value wouldn’t change, but here we are","msgtype":"m.text"},"ts":1696133141726,"senderName":"ljharb","senderId":"@ljharb:matrix.org","id":"$pbkYOvkiUKtBZgqOFSi4RHagOIWUdu4F2eyCl8gkewc"},
{"content":{"body":"My understanding is that Proxies don't have a memory. The invariants that involve time are enforced by comparing the result to the same call made to the target object. So the invariants would be broken if the target object has broken the invariant, but hosts are not supposed to create objects that break the invariants  ","format":"org.matrix.custom.html","formatted_body":"My understanding is that Proxies don't have a memory. The invariants that involve time are enforced by comparing the result to the same call made to the target object. So the invariants would be broken if the target object has broken the invariant, but hosts are not supposed to create objects that break the invariants  ","msgtype":"m.text"},"ts":1696154299222,"senderName":"Ashley Claymore","senderId":"@aclaymore:matrix.org","id":"$pBBpOh9IaA4kceq1p-Zw9N_Ci6uCCePs2h7GvCqZpFI"},
{"content":{"body":"> <@littledan:matrix.org> What if we made a function like Error.raise instead of adding syntax?\n\nrbuckton: I'd like to bring to your attention a TypeScript limitation that seriously impedes the usage of any function call that unconditionally throws like this. I suspect it would also be a problem that needs to be solved for throw expressions in general: https://github.com/microsoft/TypeScript/issues/50739","format":"org.matrix.custom.html","formatted_body":"<mx-reply><blockquote><a href=\"https://matrix.to/#/!WgJwmjBNZEXhJnXHXw:matrix.org/$5ilOORfoV4KaHH7aJHC4A9UR3PSojlapF48L0s-G0Jk?via=matrix.org&via=igalia.com&via=mozilla.org\">In reply to</a> <a href=\"https://matrix.to/#/@littledan:matrix.org\">@littledan:matrix.org</a><br>What if we made a function like Error.raise instead of adding syntax?</blockquote></mx-reply><a href=\"https://matrix.to/#/@rbuckton:matrix.org\">rbuckton</a>: I'd like to bring to your attention a TypeScript limitation that seriously impedes the usage of any function call that unconditionally throws like this. I suspect it would also be a problem that needs to be solved for throw expressions in general: https://github.com/microsoft/TypeScript/issues/50739","m.mentions":{"user_ids":["@littledan:matrix.org","@rbuckton:matrix.org"]},"m.relates_to":{"m.in_reply_to":{"event_id":"$5ilOORfoV4KaHH7aJHC4A9UR3PSojlapF48L0s-G0Jk"}},"msgtype":"m.text"},"ts":1696199751123,"senderName":"Mathieu Hofman","senderId":"@mhofman:matrix.org","id":"$DEWWDEFMwQ_YwvhZogbYdPhup4gYeQBcMS-zNGc3MSc"}
]